repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.3.0  # Use the ref you want to point at
        hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-docstring-first
    -   repo: https://github.com/pycqa/isort
        rev: 5.10.1
        hooks:
        - id: isort
          name: isort (python)
    -   repo: https://github.com/pre-commit/pygrep-hooks
        rev: v1.9.0  # Use the ref you want to point at
        hooks:
        -   id: python-use-type-annotations
    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: v1.1.1  # Use the sha / tag you want to point at
        hooks:
        -   id: mypy
            additional_dependencies: ["types-pytz"]
    -   repo: https://github.com/PyCQA/autoflake
        rev: v2.0.2
        hooks:
            -   id: autoflake
# This hook is still too restrictive. We should if we want to add it or not.
#    -   repo: https://github.com/pycqa/pydocstyle
#        rev: 4.0.0  # pick a git hash / tag to point to
#        hooks:
#        -   id: pydocstyle
#
#            -   --select=
#                D100,
#                D101,
#                D102,
#                D103,
#                D104,
#                D105,
#                D106,
#                D107,
