name: Build Docs
on:
  push:
    branches:
      - gh-pages

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.4"

      - name: Install Poetry Action
        uses: snok/install-poetry@v1.3.3

      - name: Cache Poetry virtualenv
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Set Poetry config
        run: |
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~/.virtualenvs

      - name: Install Dependencies (only for docs)
        run: poetry install --group docs
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Build dependencies and publish
        run: mkdocs gh-deploy --force --clean --verbose
